import Head from 'next/head';
import PaymentForm from '../components/form';
import s from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Payment App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.wrapper}>
        <h1>Put your card data</h1>
      </div>

      <PaymentForm />
    </div>
  );
}
